Repository nijesmik/42-algo-study, pull requests merged in 2024-02, with the labels that each got.

#39 [week06] seoson
  seoson/week6/1654.cpp
  seoson/week6/16927.cpp
  seoson/week6/17144.cpp
  seoson/week6/1790.cpp
  seoson/week7/2217.cpp
Labels: 화(정답), 토(정답), 수(오답), 금(오답)

#40 [week06] gykoh
  gykoh/1654.cpp
  gykoh/16927.cpp
  gykoh/1790.cpp
Labels: 화(정답), 금(정답), 수(오답)

#41 [week06] sejinkim
  sejinkim/week06/랜선_자르기.java
  sejinkim/week06/미세먼지_안녕.java
  sejinkim/week06/배열_돌리기_2.java
  sejinkim/week06/수_이어_쓰기_2.java
Labels: 화(정답), 수(정답), 금(정답), 토(정답)

#42 [week06] jihykim2
  jihykim2/week06/1654.cpp
  jihykim2/week06/17144.cpp
  jihykim2/week06/1790.cpp
Labels: 화(정답), 금(정답), 토(정답)

#43 [week06] eushin
  eushin/week6/BOJ_ 1654.cpp
  eushin/week6/BOJ_16927.cpp
  eushin/week6/BOJ_1790.cpp
  eushin/week7/BOJ_2217.cpp
Labels: 화(정답), 금(정답), 수(오답)

#44 [week06] sgo
  sgo/week6/랜선_자르기.java
  sgo/week6/미세먼지_안녕!.java
  sgo/week6/배열_돌리기_2.java
  sgo/week6/수_이어_쓰기_2.java
Labels: 화(정답), 수(정답), 금(정답), 토(정답)

#45 [week07] sgo
  sgo/week7/로프.java
  sgo/week7/배열_돌리기_3.java
  sgo/week7/수_묶기.java
  sgo/week7/주사위_굴리기.java
Labels: 문제1(정답), 문제2(정답), 문제3(정답), 문제4(정답)

#46 [week07] sejinkim
  sejinkim/week07/로프.java
  sejinkim/week07/배열_돌리기_3.java
  sejinkim/week07/수_묶기.java
  sejinkim/week07/주사위_굴리기.java
Labels: 문제1(정답), 문제2(정답), 문제3(정답), 문제4(정답)

#48 [week07] jihykim2
  jihykim2/week07/14499.cpp
  jihykim2/week07/16935.cpp
  jihykim2/week07/1744.cpp
  jihykim2/week07/2217.cpp
Labels: 문제1(정답), 문제2(정답), 문제3(정답), 문제4(오답)

#49 [week07] eushin
  eushin/week7/BOJ_14499.cpp
  eushin/week7/BOJ_1744.cpp
Labels: 문제1(정답), 문제2(정답), 문제3(정답)

#50 [week07] gykoh
  gykoh/2217.cpp
Labels: 문제1(정답)

#56 [week08] sejinkim
  sejinkim/week08/리모컨.java
  sejinkim/week08/배열_돌리기_1.java
  sejinkim/week08/사탕_게임.java
  sejinkim/week08/야구.java
Labels: 문제1(정답), 문제2(정답), 문제3(정답), 문제4(정답)

#55 [week08] eushin
  eushin/week7/BOJ_6935.cpp
  eushin/week8/BOJ_1107.cpp
  eushin/week8/BOJ_16926.cpp
  eushin/week8/BOJ_17281.cpp
  eushin/week8/BOJ_3085.cpp
Labels: 문제1(정답), 문제2(정답), 문제3(정답), 문제4(정답)

#52 [week08] sgo
  week8/⚾.java
  week8/리모컨.java
  week8/배열_돌리기_1.java
  week8/사탕_게임.java
Labels: 문제1(정답), 문제2(정답), 문제3(정답), 문제4(정답)

#51 [week08] seoson
  seoson/week8/1107.cpp
  seoson/week8/16926.cpp
  seoson/week8/17281.cpp
  seoson/week8/3085.cpp
Labels: 문제1(정답), 문제2(정답), 문제4(정답), 문제3(오답)

#54 [week08] jihykim2
  jihykim2/week08/3085.cpp
Labels: 문제1

#53 [week08] gykoh
  gykoh/17281.cpp
  gykoh/3085.cpp
Labels: 문제1, 문제2

#61 [week09] sejinkim
  sejinkim/week09/불.java
  sejinkim/week09/비밀_이메일.java
  sejinkim/week09/아기_상어_2.java
  sejinkim/week09/이름_궁합.java
  sejinkim/week09/캐슬_디펜스.java
Labels: 문제1, 문제2, 문제3, 문제4, 문제5

#60 [week09] eushin
  eushin/week9/BOJ_15312.cpp
  eushin/week9/BOJ_17086.cpp
  eushin/week9/BOJ_17135.cpp
  eushin/week9/BOJ_2999.cpp
  eushin/week9/BOJ_4179.cpp
Labels: 문제1, 문제2, 문제3, 문제4, 문제5

#59 [week09] gykoh
  gykoh/15312.cpp
  gykoh/17086.cpp
  gykoh/17135.cpp
  gykoh/2999.cpp
  gykoh/4179.cpp
Labels: 문제1, 문제2, 문제3, 문제4, 문제5

#58 [week09] seoson
  seoson/week9/15312.cpp
  seoson/week9/17086.cpp
  seoson/week9/17135.cpp
  seoson/week9/2999.cpp
  seoson/week9/4179.cpp
Labels: 문제1, 문제2, 문제3, 문제4, 문제5

#57 [week09] sgo
  sgo/week8/⚾.java
  sgo/week8/리모컨.java
  sgo/week8/배열_돌리기_1.java
  sgo/week8/사탕_게임.java
  sgo/week9/불!.java
  sgo/week9/비밀_이메일.java
  sgo/week9/아기_상어_2.java
  sgo/week9/이름_궁합.java
  sgo/week9/캐슬_디펜스.java
  sgo/날짜_계산.java
  sgo/늑대와_양.java
  sgo/치킨_배달.java
  sgo/톱니바퀴.java
Labels: 문제1, 문제2, 문제3, 문제4, 문제5
